name: MoveInventory
main: me.babarix.MoveInventory.MoveInventory
version: 0.5.2
author: Babarix
database: false
description: Moves Inventory between Chest and Player.
depend: [LWC]
commands:
   mi:
      description: Moves Inventory between Chest and Player.
      usage: /mi [tc|tp|v]

